version: "3"

services:

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
    - 6379:6379
    networks:
      - demo-net


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - demo-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - demo-net

  scraper:
    build:
      context: ./monolith
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - demo-net


networks:
  demo-net:
    driver: bridge
